name: Go
on: [push]
jobs:
  V0:
    name: V0
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Install staticcheck
        run: |
          echo ::set-env name=PATH::$PATH:$(go env GOPATH)/bin
          go get -u honnef.co/go/tools/cmd/staticcheck

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          dep ensure
          fi

      - name: Build
        run: go build -v .

      - name: Test
        run: go test ./...

      - name: Go List
        run: |
          echo ::set-env name=GO_LIST::$(go list ./...)

      - name: Vet
        run: go vet $GO_LIST

      - name: Static Check
        run: staticcheck $GO_LIST


  V2:
    name: V2
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Install staticcheck
        run: |
          echo ::set-env name=PATH::$PATH:$(go env GOPATH)/bin
          go get -u honnef.co/go/tools/cmd/staticcheck

      - name: Get dependencies
        working-directory: ./v2
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          dep ensure
          fi

      - name: Build
        working-directory: ./v2
        run: go build -v .

      - name: Test
        working-directory: ./v2
        run: go test ./...

      - name: Go List
        working-directory: ./v2
        run: |
          echo ::set-env name=GO_LIST::$(go list ./...)

      - name: Vet
        working-directory: ./v2
        run: go vet $GO_LIST

      - name: Static Check
        working-directory: ./v2
        run: staticcheck $GO_LIST



