name: Go
on: [push]
jobs:
  V0:

    name: V0
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.21"]
    env:
      GOPATH: /home/runner/work/cliprompts
      GO111MODULE: "on"

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{matrix.go}}

      - name: Install deps
        shell: bash --noprofile --norc -x -eo pipefail {0}
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.3

      - name: Lint
        shell: bash --noprofile --norc -x -eo pipefail {0}
        run: |
          golangci-lint run

      - name: Test
        shell: bash --noprofile --norc -x -eo pipefail {0}
        run: |
          go test ./...

  V2:
    name: V2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.21"]
    env:
      GOPATH: /home/runner/work/cliprompts
      GO111MODULE: "on"

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{matrix.go}}

      - name: Install deps
        shell: bash --noprofile --norc -x -eo pipefail {0}
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.3

      - name: Lint
        shell: bash --noprofile --norc -x -eo pipefail {0}
        working-directory: ./v2
        run: |
          golangci-lint run

      - name: Test
        working-directory: ./v2
        shell: bash --noprofile --norc -x -eo pipefail {0}
        run: |
          go test ./...
        
